language: rust
cache: cargo

branches:
  only:
    - staging
    - trying
    - master

os:
  - linux

rust:
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      rustup component add rustfmt clippy --toolchain stable;
    fi

script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      cargo fmt --all -- --check;
    fi
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      cargo clippy --workspace --all-features --all-targets -- -D warnings;
    else
      cargo check --workspace --all-features --all-targets;
    fi
  - cargo test --workspace --all-features
