[config]
min_version = "0.30.5"
default_to_workspace = false
modify_core_tasks = { namespace = "default" }

[tasks.pre-commit-flow]
dependencies = [
    "format",
    "lint-strict",
    "check-all",
]

[tasks.lint-strict]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--all-targets", "--", "-D", "warnings"]

[tasks.check-all]
command = "cargo"
args = ["check", "--workspace", "--all-features", "--all-targets"]

[tasks.test-all]
command = "cargo"
args = ["test", "--workspace", "--all-features"]

[tasks.build-all]
command = "cargo"
args = ["build", "--workspace", "--all-features", "--all-targets"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--all-targets"]

[tasks.test-doc]
command = "cargo"
args = ["test", "--workspace", "--all-features", "--doc"]

[tasks.test-lib]
command = "cargo"
args = ["test", "--workspace", "--all-features", "--lib"]

[tasks.doc]
command = "cargo"
args = ["doc", "--all-features"]
